Table ajustes{
    id int[pk, increment]
    nombre varchar
    descripcion text
    sucursal varchar
    direccion text
    telefonos varchar
    logo varchar
    logo_auto varchar
    divisa varchar
    correo varchar
    pagina_web varchar
    create_at timestamp
    update_at timestamp
}